version: 2

defaults:
  media_type: video
  storage_format: collection
  include_patterns:
    - "**/*.mp4"
    - "**/*.mkv"
    - "**/*.mov"
    - "**/*.avi"
    - "**/*.flac"
    - "**/*.mp3"
    - "**/*.aac"
    - "**/*.m4a"
    - "**/*.wav"
    - "**/*.ogg"
    - "**/*.jpg"
    - "**/*.jpeg"
    - "**/*.png"
    - "**/*.webp"
  exclude_patterns:
    - "**/.DS_Store"
    - "**/Thumbs.db"
    - "**/*.nfo"
    - "**/*.srt"
    - "**/*.sub"

categories:
  - key: movies
    label: Movies
    default: true
    media_type: video
    storage_format: collection
    root_path: T:/Movies
    playback:
      profile: cinema
      allow_hls: true
    ui:
      sort: title
      layout: poster-grid

  - key: tv_series
    label: TV Series
    media_type: video
    storage_format: series
    root_path: T:/TV Shows
    hierarchy:
      levels:
        - name: series
          key: series
        - name: season
          key: season
        - name: episode
          key: episode
    playback:
      profile: episodic
      allow_hls: true
    ui:
      sort: air_date
      layout: series-grid

  - key: documentaries
    label: Documentaries
    media_type: video
    storage_format: collection
    root_path: T:/Documentaries
    include_patterns:
      - "**/*.mp4"
      - "**/*.mkv"
    ui:
      sort: release_date

  - key: kids
    label: Kids & Family
    media_type: video
    storage_format: collection
    root_path: T:/Kids
    playback:
      profile: safe
      enable_resume: true
    ui:
      sort: title
      layout: poster-grid

  - key: concerts
    label: Concerts & Live Shows
    media_type: video
    storage_format: collection
    root_path: T:/Music Videos
    include_patterns:
      - "**/*.mp4"
      - "**/*.mkv"
      - "**/*.flac"
    playback:
      profile: music-video

  - key: music_albums
    label: Music Albums
    media_type: audio
    storage_format: group
    root_path: T:/Music
    hierarchy:
      levels:
        - name: artist
          key: artist
        - name: album
          key: album
    include_patterns:
      - "**/*.flac"
      - "**/*.mp3"
      - "**/*.aac"
      - "**/*.m4a"
    playback:
      profile: audio-hires
      gapless: true
    ui:
      sort: artist
      layout: album-grid

  - key: audiobooks
    label: Audiobooks
    media_type: audio
    storage_format: series
    root_path: T:/Audiobooks
    hierarchy:
      levels:
        - name: series
          key: series
        - name: book
          key: book
        - name: part
          key: part
    include_patterns:
      - "**/*.m4b"
      - "**/*.mp3"
      - "**/*.aac"
    playback:
      profile: spoken-word
      remember_position: true

  - key: podcasts
    label: Podcasts
    media_type: audio
    storage_format: series
    root_path: T:/Podcasts
    hierarchy:
      levels:
        - name: show
          key: show
        - name: season
          key: season
        - name: episode
          key: episode
    include_patterns:
      - "**/*.mp3"
      - "**/*.m4a"
    playback:
      profile: spoken-word
      remember_position: true

  - key: photos
    label: Photos
    media_type: image
    storage_format: collection
    root_path: T:/Photos
    include_patterns:
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.png"
      - "**/*.webp"
    ui:
      layout: gallery
      sort: captured_date

  - key: wallpapers
    label: Wallpapers & Artwork
    media_type: image
    storage_format: group
    root_path: T:/Wallpapers
    include_patterns:
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.png"
      - "**/*.webp"
    playback:
      profile: still-image
    ui:
      layout: mosaic

validation:
  strict: true
  allow_missing: false
